[workspace]

members = [
    "pine64-boot",
    "pine64",
    "pine64-hal",
    "pine64-lts-bsp",
    "examples/uart0",
    "examples/hdmi-raw-display",
    "examples/hdmi-raw-display-dma",
    "examples/mem2mem-dma",
]
