[package]
name = "pine64-lts-bsp"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

[dependencies]
bitfield = "0.13"

[dependencies.pine64-hal]
path = "../pine64-hal"

[dependencies.nom]
version = "5.1"
default-features = false
