[package]
name = "uart0"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

[dependencies]
pine-a64-hal = { path = "../../pine-a64-hal" }

[dependencies.pine-a64-boot]
path = "../../pine-a64-boot"
default-features = false
features = ["panic-abort"]
