[package]
name = "pine-a64-boot"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

[dependencies]
cortex-a = "3.0"
r0 = "1.0"

[dependencies.pine-a64-hal]
path = "../pine-a64-hal"
optional = true

[features]
default = []
panic-abort = []
panic-uart = ["pine-a64-hal"]
