[package]
name = "hs-timer-delay"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

[dependencies]

[dependencies.pine64-hal]
path = "../../pine64-hal"

[dependencies.pine64-boot]
path = "../../pine64-boot"
default-features = false
features = ["panic-uart"]
